function M = npend_alphas_NE_M_1(I1,L1,d1,g,m1,omega1,theta1,fric)
%NPEND_ALPHAS_NE_M_1
%    M = NPEND_ALPHAS_NE_M_1(I1,L1,D1,G,M1,OMEGA1,THETA1,FRIC)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Dec-2018 00:00:20

t2 = cos(theta1);
t3 = d1.^2;
t4 = sin(theta1);
M = [-I1-m1.*t2.^2.*t3-m1.*t3.*t4.^2];
