function b = npend_alphas_NE_b_2(in1,in2,in3,g,in5,in6,in7,fric)
%NPEND_ALPHAS_NE_B_2
%    B = NPEND_ALPHAS_NE_B_2(IN1,IN2,IN3,G,IN5,IN6,IN7,FRIC)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Dec-2018 00:00:22

L1 = in2(1,:);
d1 = in3(1,:);
d2 = in3(2,:);
m1 = in5(1,:);
m2 = in5(2,:);
omega1 = in6(1,:);
omega2 = in6(2,:);
theta1 = in7(1,:);
theta2 = in7(2,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = omega1.^2;
t5 = sin(theta1);
t6 = L1-d1;
t7 = omega2.^2;
t8 = sin(theta2);
t9 = L1.*t5;
t10 = d2.*t8;
t11 = t9+t10;
t12 = L1.*t2;
t13 = d2.*t3;
t14 = t12+t13;
t15 = d1.*t2;
t16 = t2.*t6;
t17 = t15+t16;
t18 = t4.*t17;
t19 = d2.*t3.*t7;
t20 = t18+t19;
t21 = d1.*t5;
t22 = t5.*t6;
t23 = t21+t22;
t24 = t4.*t23;
t25 = d2.*t7.*t8;
t26 = t24+t25;
b = [g.*m2.*t11+m2.*t11.*t20-m2.*t14.*t26+d1.*g.*m1.*t5+fric.*omega2.*t3.*t14.*(1.0./1.0e2)+fric.*omega2.*t8.*t11.*(1.0./1.0e2)+d1.*fric.*omega1.*t2.^2.*(1.0./1.0e2)+d1.*fric.*omega1.*t5.^2.*(1.0./1.0e2);d2.*g.*m2.*t8+d2.*m2.*t8.*t20-d2.*m2.*t3.*t26+d2.*fric.*omega2.*t3.^2.*(1.0./1.0e2)+d2.*fric.*omega2.*t8.^2.*(1.0./1.0e2)];
