function M = npend_alphas_NE_M_2(in1,in2,in3,g,in5,in6,in7,fric)
%NPEND_ALPHAS_NE_M_2
%    M = NPEND_ALPHAS_NE_M_2(IN1,IN2,IN3,G,IN5,IN6,IN7,FRIC)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Dec-2018 00:00:21

I1 = in1(1,:);
I2 = in1(2,:);
L1 = in2(1,:);
d1 = in3(1,:);
d2 = in3(2,:);
m1 = in5(1,:);
m2 = in5(2,:);
theta1 = in7(1,:);
theta2 = in7(2,:);
t2 = sin(theta1);
t3 = cos(theta1);
t4 = d1.^2;
t5 = L1-d1;
t6 = cos(theta2);
t7 = L1.*t3;
t8 = d2.*t6;
t9 = t7+t8;
t10 = sin(theta2);
t11 = L1.*t2;
t12 = d2.*t10;
t13 = t11+t12;
t14 = d1.*t3;
t15 = t3.*t5;
t16 = t14+t15;
t17 = d1.*t2;
t18 = t2.*t5;
t19 = t17+t18;
t20 = d2.^2;
M = reshape([-I1-m1.*t2.^2.*t4-m1.*t3.^2.*t4-m2.*t9.*t16-m2.*t13.*t19,-d2.*m2.*t6.*t16-d2.*m2.*t10.*t19,-I2-d2.*m2.*t6.*t9-d2.*m2.*t10.*t13,-I2-m2.*t6.^2.*t20-m2.*t10.^2.*t20],[2,2]);
