function M = npend_alphas_NE_M_3(in1,in2,in3,g,in5,in6,in7,fric)
%NPEND_ALPHAS_NE_M_3
%    M = NPEND_ALPHAS_NE_M_3(IN1,IN2,IN3,G,IN5,IN6,IN7,FRIC)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Dec-2018 00:00:23

I1 = in1(1,:);
I2 = in1(2,:);
I3 = in1(3,:);
L1 = in2(1,:);
L2 = in2(2,:);
d1 = in3(1,:);
d2 = in3(2,:);
d3 = in3(3,:);
m1 = in5(1,:);
m2 = in5(2,:);
m3 = in5(3,:);
theta1 = in7(1,:);
theta2 = in7(2,:);
theta3 = in7(3,:);
t2 = sin(theta1);
t3 = cos(theta1);
t4 = L1-d1;
t5 = d1.*t2;
t6 = t2.*t4;
t7 = t5+t6;
t8 = L1.*t2;
t9 = sin(theta2);
t10 = d1.^2;
t11 = L1.*t3;
t12 = cos(theta2);
t13 = d1.*t3;
t14 = t3.*t4;
t15 = t13+t14;
t16 = d2.*t12;
t17 = L2.*t12;
t18 = cos(theta3);
t19 = d3.*t18;
t20 = t11+t17+t19;
t21 = d2.*t9;
t22 = L2-d2;
t23 = L2.*t9;
t24 = sin(theta3);
t25 = d3.*t24;
t26 = t8+t23+t25;
t27 = t11+t16;
t28 = t8+t21;
t29 = t23+t25;
t30 = t9.*t22;
t31 = t21+t30;
t32 = d2.^2;
t33 = t17+t19;
t34 = t12.*t22;
t35 = t16+t34;
t36 = d3.^2;
M = reshape([-I1-m1.*t2.^2.*t10-m1.*t3.^2.*t10-m3.*t7.*t26-m2.*t7.*t28-m3.*t15.*t20-m2.*t15.*t27,-m3.*t7.*t29-m3.*t15.*t33-d2.*m2.*t7.*t9-d2.*m2.*t12.*t15,-d3.*m3.*t7.*t24-d3.*m3.*t15.*t18,-I2-m3.*t20.*t35-m3.*t26.*t31-d2.*m2.*t9.*t28-d2.*m2.*t12.*t27,-I2-m2.*t9.^2.*t32-m2.*t12.^2.*t32-m3.*t29.*t31-m3.*t33.*t35,-d3.*m3.*t18.*t35-d3.*m3.*t24.*t31,-I3-d3.*m3.*t18.*t20-d3.*m3.*t24.*t26,-I3-d3.*m3.*t18.*t33-d3.*m3.*t24.*t29,-I3-m3.*t18.^2.*t36-m3.*t24.^2.*t36],[3,3]);
