function b = npend_alphas_NE_b_1(I1,L1,d1,g,m1,omega1,theta1,fric)
%NPEND_ALPHAS_NE_B_1
%    B = NPEND_ALPHAS_NE_B_1(I1,L1,D1,G,M1,OMEGA1,THETA1,FRIC)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Dec-2018 00:00:21

t2 = cos(theta1);
t3 = sin(theta1);
b = [d1.*g.*m1.*t3+d1.*fric.*omega1.*t2.^2.*(1.0./1.0e2)+d1.*fric.*omega1.*t3.^2.*(1.0./1.0e2)];
