function K = nmodeK_1(I1,L1,d1,g,m1,omega1,theta1)
%NMODEK_1
%    K = NMODEK_1(I1,L1,D1,G,M1,OMEGA1,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Dec-2018 19:16:12

K = [d1.*conj(g).*conj(m1)];
