function M = nmodeM_1(I1,L1,d1,g,m1,omega1,theta1)
%NMODEM_1
%    M = NMODEM_1(I1,L1,D1,G,M1,OMEGA1,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Dec-2018 19:16:11

M = [I1+d1.*m1.*conj(d1)];
