function M = nmodeM_2(in1,in2,in3,g,in5,in6,in7)
%NMODEM_2
%    M = NMODEM_2(IN1,IN2,IN3,G,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Dec-2018 19:17:16

I1 = in1(1,:);
I2 = in1(2,:);
L1 = in2(1,:);
d1 = in3(1,:);
d2 = in3(2,:);
m1 = in5(1,:);
m2 = in5(2,:);
t2 = conj(L1);
t3 = conj(d2);
t4 = L1.*t3;
t5 = d2.*t2;
t6 = t4+t5;
t7 = m2.*t6.*(1.0./2.0);
M = reshape([I1+L1.*m2.*t2+d1.*m1.*conj(d1),t7,t7,I2+d2.*m2.*t3],[2,2]);
