function M = nmodeM_3(in1,in2,in3,g,in5,in6,in7)
%NMODEM_3
%    M = NMODEM_3(IN1,IN2,IN3,G,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Dec-2018 13:25:26

I1 = in1(1,:);
I2 = in1(2,:);
I3 = in1(3,:);
L1 = in2(1,:);
L2 = in2(2,:);
d1 = in3(1,:);
d2 = in3(2,:);
d3 = in3(3,:);
m1 = in5(1,:);
m2 = in5(2,:);
m3 = in5(3,:);
t2 = conj(L1);
t3 = conj(d2);
t4 = L1.*t3;
t5 = d2.*t2;
t6 = t4+t5;
t7 = m2.*t6.*(1.0./2.0);
t8 = conj(L2);
t9 = L1.*t8;
t10 = L2.*t2;
t11 = t9+t10;
t12 = m3.*t11.*(1.0./2.0);
t13 = t7+t12;
t14 = conj(d3);
t15 = L1.*t14;
t16 = d3.*t2;
t17 = t15+t16;
t18 = m3.*t17.*(1.0./2.0);
t19 = L2.*t14;
t20 = d3.*t8;
t21 = t19+t20;
t22 = m3.*t21.*(1.0./2.0);
M = reshape([I1+L1.*m2.*t2+L1.*m3.*t2+d1.*m1.*conj(d1),t13,t18,t13,I2+L2.*m3.*t8+d2.*m2.*t3,t22,t18,t22,I3+d3.*m3.*t14],[3,3]);
