function K = nmodeK_2(in1,in2,in3,g,in5,in6,in7)
%NMODEK_2
%    K = NMODEK_2(IN1,IN2,IN3,G,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Dec-2018 19:17:16

L1 = in2(1,:);
d1 = in3(1,:);
d2 = in3(2,:);
m1 = in5(1,:);
m2 = in5(2,:);
omega1 = in6(1,:);
omega2 = in6(2,:);
t2 = conj(L1);
t3 = omega1.*t2;
t4 = conj(d2);
t5 = omega2.*t4;
t6 = t3+t5;
t7 = L1.*omega1;
t8 = d2.*omega2;
t9 = t7+t8;
t10 = conj(m2);
t11 = conj(g);
t12 = L1.*omega2.*t4;
t13 = d2.*omega2.*t2;
t14 = t12+t13;
t15 = m2.*omega2.*t14.*(1.0./2.0);
t16 = L1.*omega1.*omega2.*t4;
t17 = d2.*omega1.*omega2.*t2;
t18 = t16+t17;
t19 = L1.*omega1.*t4;
t20 = d2.*omega1.*t2;
t21 = t19+t20;
K = reshape([t15+t10.*(L1.*omega1.*t6+omega1.*t2.*t9-L1.*omega1.^2.*t2.*2.0).*(1.0./2.0)+d1.*t11.*conj(m1)-m2.*omega1.*(L1.*t6+t2.*t9-L1.*omega1.*t2.*2.0).*(1.0./2.0)+L1.*t10.*t11,t10.*t18.*(-1.0./2.0)-m2.*omega1.*t21.*(1.0./2.0)+m2.*omega2.*t21.*(1.0./2.0),-t15-t10.*t18.*(1.0./2.0)+m2.*omega1.*t14.*(1.0./2.0),t10.*(d2.*omega2.^2.*t4.*-2.0+d2.*omega2.*t6+omega2.*t4.*t9).*(1.0./2.0)+d2.*t10.*t11+m2.*omega1.*t21.*(1.0./2.0)-m2.*omega2.*(d2.*t6+t4.*t9-d2.*omega2.*t4.*2.0).*(1.0./2.0)],[2,2]);
