function b = npend_alphas_Lagrange_b_2(in1,in2,in3,g,in5,in6,in7)
%NPEND_ALPHAS_LAGRANGE_B_2
%    B = NPEND_ALPHAS_LAGRANGE_B_2(IN1,IN2,IN3,G,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    03-Dec-2018 23:32:28

L1 = in2(1,:);
d1 = in3(1,:);
d2 = in3(2,:);
m1 = in5(1,:);
m2 = in5(2,:);
omega1 = in6(1,:);
omega2 = in6(2,:);
theta1 = in7(1,:);
theta2 = in7(2,:);
t2 = cos(theta1);
t3 = conj(L1);
t4 = sin(theta1);
t5 = conj(d2);
t6 = cos(theta2);
t7 = sin(theta2);
t8 = d2.*omega2.*t6;
t9 = L1.*omega1.*t2;
t10 = t8+t9;
t11 = L1.*omega1.*t4;
t12 = d2.*omega2.*t7;
t13 = t11+t12;
t14 = omega1.*t2.*t3;
t15 = omega2.*t5.*t6;
t16 = t14+t15;
t17 = omega1.*t3.*t4;
t18 = omega2.*t5.*t7;
t19 = t17+t18;
t20 = conj(m2);
t21 = conj(g);
b = [t20.*(L1.*omega1.*t4.*t16-L1.*omega1.*t2.*t19+omega1.*t3.*t4.*t10-omega1.*t2.*t3.*t13).*(-1.0./2.0)+m2.*omega1.*(L1.*t4.*t16-L1.*t2.*t19+t3.*t4.*t10-t2.*t3.*t13).*(1.0./2.0)+m2.*omega2.*(L1.*omega2.*t2.*t5.*t7-L1.*omega2.*t4.*t5.*t6+d2.*omega2.*t2.*t3.*t7-d2.*omega2.*t3.*t4.*t6).*(1.0./2.0)-L1.*t4.*t20.*t21-d1.*t4.*t21.*conj(m1);t20.*(d2.*omega2.*t7.*t16-d2.*omega2.*t6.*t19+omega2.*t5.*t7.*t10-omega2.*t5.*t6.*t13).*(-1.0./2.0)+m2.*omega2.*(d2.*t7.*t16-d2.*t6.*t19+t5.*t7.*t10-t5.*t6.*t13).*(1.0./2.0)-m2.*omega1.*(L1.*omega1.*t2.*t5.*t7-L1.*omega1.*t4.*t5.*t6+d2.*omega1.*t2.*t3.*t7-d2.*omega1.*t3.*t4.*t6).*(1.0./2.0)-d2.*t7.*t20.*t21];
