function b = npend_alphas_DAE_b_2(in1,in2,in3,g,in5,in6,in7,in8)
%NPEND_ALPHAS_DAE_B_2
%    B = NPEND_ALPHAS_DAE_B_2(IN1,IN2,IN3,G,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Dec-2018 09:17:23

L1 = in2(1,:);
d1 = in3(1,:);
d2 = in3(2,:);
d_a1 = in8(:,1);
d_a2 = in8(:,2);
m1 = in5(1,:);
m2 = in5(2,:);
omega1 = in6(1,:);
omega2 = in6(2,:);
theta1 = in7(1,:);
theta2 = in7(2,:);
t2 = omega1.^2;
t3 = sin(theta1);
t4 = cos(theta1);
t5 = d1.*t2.*t4;
t6 = omega2.^2;
b = [0.0;-g.*m1;0.0;-g.*m2;0.0;0.0;d_a1-d1.*t2.*t3;d_a2+t5;-d2.*t6.*sin(theta2)-L1.*t2.*t3+d1.*t2.*t3;-t5+d2.*t6.*cos(theta2)+L1.*t2.*t4];
