function b = npend_alphas_DAE_b_1(I1,L1,d1,g,m1,omega1,theta1,in8)
%NPEND_ALPHAS_DAE_B_1
%    B = NPEND_ALPHAS_DAE_B_1(I1,L1,D1,G,M1,OMEGA1,THETA1,IN8)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Dec-2018 02:30:11

d_a1 = in8(:,1);
d_a2 = in8(:,2);
t2 = omega1.^2;
b = [0.0;-g.*m1;0.0;d_a1-d1.*t2.*sin(theta1);d_a2+d1.*t2.*cos(theta1)];
