function b = nlink_alphas_DAE_b_31(in1,in2,in3,g,in5,in6,in7,rest,in9)
%NLINK_ALPHAS_DAE_B_31
%    B = NLINK_ALPHAS_DAE_B_31(IN1,IN2,IN3,G,IN5,IN6,IN7,REST,IN9)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Dec-2018 23:08:10

L28 = in2(28,:);
d28 = in3(28,:);
d29 = in3(29,:);
m30 = in5(30,:);
omega28 = in6(28,:);
omega29 = in6(29,:);
theta28 = in7(28,:);
theta29 = in7(29,:);
t2 = omega28.^2;
t3 = sin(theta28);
t4 = cos(theta28);
t5 = omega29.^2;
b = [0.0;-g.*m30;0.0;-d29.*t5.*sin(theta29)-L28.*t2.*t3+d28.*t2.*t3;d29.*t5.*cos(theta29)+L28.*t2.*t4-d28.*t2.*t4];
