function b = nlink_alphas_DAE_b_3(in1,in2,in3,g,in5,in6,in7,rest,in9)
%NLINK_ALPHAS_DAE_B_3
%    B = NLINK_ALPHAS_DAE_B_3(IN1,IN2,IN3,G,IN5,IN6,IN7,REST,IN9)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Dec-2018 16:22:31

L1 = in2(1,:);
L2 = in2(2,:);
d1 = in3(1,:);
d2 = in3(2,:);
d2_a1 = in9(:,1);
d2_a2 = in9(:,2);
m1 = in5(1,:);
m2 = in5(2,:);
omega1 = in6(1,:);
omega2 = in6(2,:);
theta1 = in7(1,:);
theta2 = in7(2,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = omega1.^2;
t5 = d1.*t2.*t4;
t6 = omega2.^2;
t7 = sin(theta2);
t8 = cos(theta2);
t9 = d2.*t6.*t8;
b = [0.0;-g.*m1;0.0;-g.*m2;d1.*omega1.*rest.*t2.^2.*(-1.0./2.0e2)-d1.*omega1.*rest.*t3.^2.*(1.0./2.0e2);0.0;-d1.*t3.*t4;t5;-L1.*t3.*t4+d1.*t3.*t4-d2.*t6.*t7;-t5+t9+L1.*t2.*t4;-d2_a1+L2.*t6.*t7-d2.*t6.*t7;-d2_a2+t9-L2.*t6.*t8];
